### ISSUE TITLE
Won't see journals and won't recognize CMDR login

### ISSUE THREAD

**Issue by Eckee** [jixxed/ed-odyssey-materials-helper#494] opened 2024-12-22 03:47 UTC
Hi, it says "No Odyssey journals found" and "Please login to the game"

I tried restarting everything, running the app as administrator.

Journals are in the default directory and other apps I use can read them.
Using Steam, Win11 Pro, no antivirus
![edomh](https://github.com/user-attachments/assets/613a286a-c96e-4c52-a2f4-6873ab02017e)

**Comment by jixxed** [comment] 2024-12-29 10:52
**never run as admin**
have you logged into a game session?
can you generate a support package under settings and upload it here?

**Comment by Eckee** [comment] 2024-12-29 11:17
Yes, I have logged in multiple times. I also uninstalled/installed again.

[support.2024-12-29_14.16.37.972.zip](https://github.com/user-attachments/files/18269274/support.2024-12-29_14.16.37.972.zip)

**Comment by jixxed** [comment] 2024-12-29 11:28
looks like an issue in one of your journals. 2.129 is being released now and should be able to handle the issue.

**Comment by Eckee** [comment] 2024-12-29 18:42
Thank you. I'll check after the update.

**Comment by jixxed** [comment] 2024-12-30 23:49
looks like Journal.2024-12-10T134742.01.log is your issue. can you share it?

**Comment by jixxed** [comment] 2024-12-31 00:31
If possible, please share your entire journal folder. you can send it over discord in a direct message. Normally the exception that is occurring now is a result of not having journal files, but you clearly do. having your journal folder allows me to reproduce the issue.

**Comment by jixxed** [comment] 2024-12-31 12:38
fixed in next release

**Closed by jixxed** 2024-12-31 12:38 UTC
