### ISSUE TITLE
Cant start latest release

### ISSUE THREAD

**Issue by dipperside** [jixxed/ed-odyssey-materials-helper#117] opened 2022-12-11 19:15 UTC
Please help!

I had the previous version of mat-helper and it worked fine. But I decided to update for the new one and then I got this error when running the app. It doesn't matter if it's the portable version or the msi version - the error is the same.

![image](https://user-images.githubusercontent.com/23295612/206923935-4a252a25-e7d0-4d81-ba86-21b977753e9c.png)

**Comment by jixxed** [comment] 2022-12-11 19:50
This is caused by a corruption in the status file of the game. if you login to the game, that file will get written to again and the app will launch normally. this will be fixed in the next release.

**Comment by jixxed** [comment] 2022-12-21 19:53
added in 2.5

**Closed by jixxed** 2022-12-21 19:53 UTC
