### ISSUE TITLE
No Journal found

### ISSUE THREAD

**Issue by sergeyp7v** [jixxed/ed-odyssey-materials-helper#44] opened 2021-08-10 08:04 UTC
Hello there,
I have problem with the Helper since version 1.27-1.30, no commander's journal detected.
Version 1.26 detect journal good.
Attached journal file.
Game localization -- Russian

![001](https://user-images.githubusercontent.com/88708312/128830513-9d30c249-0a3d-4b6e-8d9e-d5c7aa16d0ec.jpg)
[Journal.210810104602.01.log](https://github.com/jixxed/ed-odyssey-materials-helper/files/6959998/Journal.210810104602.01.log)

**Comment by jixxed** [comment] 2021-08-10 13:38
appears to be a charset issue, possibly caused by the Russian letters. I did not experience this issue running the game in the Russian language. will fix this in the next version.

**Comment by jixxed** [comment] 2021-08-10 16:52
fixed in 1.39

**Closed by jixxed** 2021-08-10 16:52 UTC
